services:
  prefect:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"  # Prefect UI
      - "4201:4201"  # Prefect API
    environment:
      PREFECT_UI_URL: http://localhost:4200
      
  eccc_buoy_parser:
    build:
      context: ./ECCC_Buoy_Parser
      dockerfile: Dockerfile
    volumes:
      - ./datasets:/app/datasets
      - ./ECCC_Buoy_Parser/app/config:/app/config
      - ./ECCC_Buoy_Parser/app/data:/app/data
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
    
    #profiles:
    #  - tools
    #volumes:
    	
    #  - ./harvest_config.yaml:/app/harvester/harvest_config.yaml
    #  - ./harvester_cache:/app/harvester/harvester_cache
    #  - ./harvest:/app/harvester/harvest
    #env_file:
    #  - .env

   
  erddap:
    image: axiom/docker-erddap:v2.28.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt
      - ./erddap/content:/usr/local/tomcat/content/erddap
      - ./erddap/data:/erddapData
      - ./erddap/datasets.d:/datasets.d
      - ./datasets:/datasets
      - ./scripts:/scripts
    environment:
      #note: these can also be set in /usr/local/tomcat/bin/config.sh
      ERDDAP_MIN_MEMORY: 1G
      ERDDAP_MAX_MEMORY: 2G
      ERDDAP_bigParentDirectory: /erddapData/
      ERDDAP_baseUrl: http://localhost:8080
      ERDDAP_baseHttpsUrl: https://localhost:8080
      ERDDAP_flagKeyKey: changed
      ERDDAP_emailEverythingTo: this+goes+nowhere@doesnotexist.ioos.us
      ERDDAP_emailDailyReportTo:
      ERDDAP_emailFromAddress:
      ERDDAP_emailUserName:
      ERDDAP_emailPassword:
      ERDDAP_emailProperties:
      ERDDAP_emailSmtpHost:
      ERDDAP_emailSmtpPort:
      ERDDAP_adminInstitution: Integrated Ocean Observing System (IOOS)
      ERDDAP_adminInstitutionUrl: https://ioos.github.io/
      ERDDAP_adminIndividualName: IOOS Data Manager
      ERDDAP_adminPosition: Data Manager
      ERDDAP_adminPhone: "240-533-9444"
      ERDDAP_adminAddress: "1315 East-West Highway 2nd Floor"
      ERDDAP_adminCity: Silver Spring
      ERDDAP_adminStateOrProvince: MD
      ERDDAP_adminPostalCode: "20910"
      ERDDAP_adminCountry: USA
      ERDDAP_adminEmail: data.ioos@noaa.gov
